Fixed buildout.cfg by pinning more versions.
I got this while running buildout:

While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis.
Error: The requirement ('flake8>=2.4.0') is not allowed by your [versions] constraint (2.3.0)

This is because we got a too new plone.recipe.codeanalysis.
Fixed by actually using that newer codeanalysis version and pinning flake8 to a newer one.
Plus more version pins to avoid this kind of problems later on.

Note that a few remained unpinned, like zc.buildout and plone.app.event,
though this last one is pinned to a version restriction (less than 2.0).