Encode the absolute_target_url as utf-8 string
This is to make sure url can be converted to string lower in the stack. If not you can get errors like:
Traceback (innermost last): 
Module ZPublisher.Publish, line 138, in publish 
Module ZPublisher.mapply, line 77, in mapply 
Module ZPublisher.Publish, line 48, in call_object 
Module plone.app.contenttypes.browser.link_redirect_view, line 56, in __call__ 
Module ZPublisher.HTTPResponse, line 609, in redirect 
Module ZPublisher.HTTPResponse, line 331, in setHeader 
Module ZPublisher.HTTPResponse, line 134, in _scrubHeader 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)